#! /bin/sh
SCRIPTS="${HOME}/.config/bspwm/scripts"

"${SCRIPTS}/autostart.sh"


# workspaces
bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Slack desktop='^4'state=tiled
bspc rule -a TelegramDesktop desktop='^4' state=tiled
bspc rule -a Spotify desktop='^6' focus=on
bspc rule -a mpv state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a 1Password state=floating
