
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█


# See https://wiki.hyprland.org/Configuring/Monitors/

# monitor = ,preferred,auto,auto
# monitor = DP-1, 2560x1080@144, 0x0, 1, bitdepth, 10
monitor=,preferred,auto,1.33


# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄


# See https://wiki.hyprland.org/Configuring/Variables/ for more

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}
