#! /bin/sh
#
######################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
######################################################



# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################
pgrep -x sxhkd > /dev/null || sxhkd &
# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           9

bspc config split_ratio          0.65
bspc config focus_follows_pointer true

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config pointer_follows_monitor true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#908caa"
bspc config focused_border_color "#9ccfd8"

config presel_feedback_color "#9ccfd8"


# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################
bspc rule -r *:*
bspc rule -a 1Password            state=floating
bspc rule -a Slack                desktop=4
bspc rule -a firefox              desktop=1
bspc rule -a Spotify              desktop=6
bspc rule -a Lxappearance         state=floating follow=on
bspc rule -a Arandr               state=floating follow=on
bspc rule -a Galculator           state=floating follow=on
bspc rule -a floating             state=floating center=on

SCRATCH_RULES="sticky=on state=floating hidden=on"

bspc rule -a scratchpad-one       ${SCRATCH_RULES}
bspc rule -a scratchpad-two       ${SCRATCH_RULES}
bspc rule -a scratchpad-three     ${SCRATCH_RULES}
bspc rule -a scratchpad-files     ${SCRATCH_RULES}
bspc rule -a scratchpad-volume    ${SCRATCH_RULES}
bspc rule -a scratchpad-notes     ${SCRATCH_RULES}
