[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = false
enable-click = true
enable-scroll = false
reverse-scroll = false
fuzzy-match = false
occupied-scroll = true


format = <label-state> <label-mode>
; format-font = 14


label-focused-foreground = ${color.fg}
label-focused-background = ${color.bg}
label-focused-underline =  ${color.color3}
label-focused-padding-right = 2
label-focused-padding-left = 1

label-occupied-foreground = ${color.fg}
label-occupied-background = ${color.bg}
;label-occupied-underline = 
label-occupied-padding-right = 2
label-occupied-padding-left = 1

label-urgent-foreground = ${color.fg}
label-urgent-background = ${color.color1}
label-urgent-underline =  ${color.color1}
label-urgent-padding-right = 2
label-urgent-padding-left = 1

label-empty-foreground = ${color.fg}
label-empty-padding-right = 0
label-empty-padding-left = 0

; Separator in between workspaces
label-separator = " "
label-separator-foreground = ${color.color1}

label-empty =

label-empty-padding = 0
