// black
#define COLOR0 #090618
#define COLOR8 #727169

// red
#define COLOR1 #c34043
#define COLOR9 #e82424

// green
#define COLOR2 #76946a
#define COLOR10 #98bb6c

// yellow
#define COLOR3 #c0a36e
#define COLOR11 #e6c384

// blue
#define COLOR4 #7e9cd8
#define COLOR12 #7fb4ca

// magenta
#define COLOR5 #957fb8
#define COLOR13 #938aa9

// cyan
#define COLOR6 #6a9589
#define COLOR14 #7aa89f

// white
#define COLOR7 #c8c093
#define COLOR15 #dcd7ba

#define BASE_FOREGROUND #dcd7ba
#define BASE_BACKGROUND #232124
#define TERMINAL_BACKGROUND #1f1f28
#define CURSOR #dcd7ba
#define ACCENT_COLOR #45BEC4

#define SELECTED_FOREGROUND BASE_BACKGROUND
#define SELECTED_BACKGROUND ACCENT_COLOR

#define SCRATCH_NORM_FG_COLOR BASE_BACKGROUND
#define SCRATCH_NORM_BG_COLOR BASE_FOREGROUND

#define SCRATCH_SEL_FG_COLOR COLOR5
#define SCRATCH_SEL_BG_COLOR SELECTED_BACKGROUND

#define HID_NORM_FG_COLOR ACCENT_COLOR
#define HID_NORM_BG_COLOR BASE_BACKGROUND

#define HID_SEL_FG_COLOR ACCENT_COLOR
#define HID_SEL_BG_COLOR BASE_BACKGROUND

#define WS_NORM_FG_COLOR BASE_FOREGROUND
#define WS_NORM_BG_COLOR BASE_BACKGROUND

#define WS_SEL_FG_COLOR BASE_BACKGROUND
#define WS_SEL_BG_COLOR ACCENT_COLOR

#define MARKED_FG_COLOR COLOR3
#define MARKED_BG_COLOR BASE_BACKGROUND

#define BORDER COLOR6

#define WARNING_FG_COLOR COLOR11
#define WARNING_BG_COLOR BASE_BACKGROUND

#define URGENT_FG_COLOR COLOR1
#define URGENT_BG_COLOR BASE_BACKGROUND


#define TITLE_NORM_BG_COLOR BASE_BACKGROUND
#define TITLE_NORM_FG_COLOR BASE_FOREGROUND

#define TITLE_SEL_BG_COLOR ACCENT_COLOR
#define TITLE_SEL_FG_COLOR #1f1f28
#define TITLESEL #1f1f28

