# Autostart applications

exec_always --no-startup-id fix_xcursor
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id greenclip daemon
exec --no-startup-id feh --bg-fill ~/Pictures/Walls/mountains.png
exec --no-startup-id sleep 0.4s; autorandr -c
exec --no-startup-id sleep 1s; picom -b
exec --no-startup-id sleep 1s; nm-applet
exec --no-startup-id sleep 1s; blueman-applet
exec --no-startup-id sleep 1s; xautolock -time $lock_time -locker $lock
